In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import sklearn.metrics as sm
from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn import datasets

In [6]:
digits=datasets.load_digits()

In [7]:
digits

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'frame': None,
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7',
  'pixel_5_0',
  'pixel_5_1',
 

In [8]:
x=digits.data
y=digits.target

In [9]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [10]:
model=linear_model.LogisticRegression()

In [ ]:
model.fit(x_train,y_train)

In [12]:
out=model.predict(x_test)

In [14]:
out

array([0, 8, 0, 6, 3, 1, 1, 7, 1, 3, 0, 3, 3, 6, 2, 2, 6, 4, 6, 6, 3, 2,
       1, 2, 3, 4, 8, 1, 8, 5, 8, 5, 8, 0, 4, 3, 1, 4, 0, 8, 9, 5, 4, 2,
       6, 2, 2, 2, 3, 6, 4, 1, 3, 9, 9, 6, 0, 9, 0, 2, 1, 9, 8, 6, 6, 1,
       3, 8, 1, 4, 7, 7, 0, 6, 8, 6, 3, 3, 5, 4, 9, 1, 4, 0, 0, 8, 0, 7,
       9, 1, 9, 1, 0, 1, 9, 0, 1, 3, 2, 0, 1, 6, 5, 6, 4, 1, 8, 6, 8, 8,
       1, 7, 4, 5, 7, 0, 6, 5, 8, 3, 8, 7, 9, 9, 4, 1, 4, 8, 0, 5, 5, 6,
       7, 8, 1, 2, 9, 0, 9, 0, 2, 8, 3, 6, 6, 4, 8, 2, 1, 4, 9, 7, 3, 2,
       4, 3, 1, 8, 6, 0, 9, 1, 0, 9, 6, 0, 1, 0, 7, 9, 8, 2, 4, 6, 5, 1,
       9, 5, 8, 3, 1, 3, 4, 0, 9, 3, 6, 2, 8, 8, 3, 4, 7, 9, 2, 5, 0, 6,
       9, 9, 3, 6, 6, 3, 8, 1, 0, 9, 5, 1, 0, 6, 9, 7, 6, 4, 3, 5, 8, 8,
       9, 4, 7, 4, 7, 4, 3, 1, 3, 9, 5, 1, 1, 0, 0, 7, 6, 8, 4, 1, 0, 8,
       8, 8, 8, 1, 6, 1, 2, 2, 3, 0, 5, 6, 6, 9, 9, 7, 4, 7, 5, 6, 3, 5,
       2, 4, 4, 8, 2, 0, 8, 7, 7, 8, 6, 2, 5, 8, 6, 5, 6, 1, 2, 0, 1, 8,
       3, 4, 7, 3, 6, 7, 2, 3, 0, 5, 6, 1, 2, 2, 0,

In [15]:
y_test 

array([0, 8, 0, 6, 3, 1, 1, 7, 1, 3, 0, 3, 3, 6, 2, 2, 6, 4, 6, 6, 3, 2,
       1, 2, 3, 4, 8, 1, 8, 5, 8, 5, 8, 0, 4, 3, 1, 4, 0, 8, 1, 5, 4, 2,
       8, 2, 2, 2, 3, 6, 4, 1, 3, 9, 9, 6, 0, 9, 0, 2, 1, 9, 8, 6, 6, 1,
       3, 8, 1, 4, 7, 7, 0, 6, 8, 6, 3, 3, 5, 4, 9, 1, 4, 0, 0, 8, 0, 7,
       9, 1, 9, 1, 0, 1, 9, 0, 1, 3, 2, 0, 1, 6, 5, 6, 4, 1, 8, 6, 8, 8,
       1, 7, 4, 5, 7, 0, 6, 5, 8, 3, 8, 7, 9, 9, 4, 1, 4, 8, 0, 5, 5, 6,
       7, 8, 1, 3, 9, 0, 9, 0, 2, 8, 3, 6, 6, 4, 8, 2, 1, 4, 9, 7, 3, 2,
       4, 3, 1, 8, 6, 0, 5, 1, 0, 9, 6, 0, 1, 0, 7, 9, 8, 2, 4, 6, 5, 1,
       9, 5, 8, 3, 1, 3, 4, 0, 9, 3, 6, 2, 8, 8, 3, 1, 7, 9, 2, 5, 0, 6,
       9, 9, 3, 6, 6, 3, 8, 1, 0, 9, 5, 1, 0, 6, 9, 7, 6, 4, 3, 5, 8, 8,
       9, 4, 7, 4, 7, 4, 3, 1, 1, 9, 5, 1, 1, 0, 0, 7, 6, 6, 4, 1, 0, 8,
       8, 8, 8, 1, 6, 1, 2, 2, 3, 0, 5, 6, 6, 9, 9, 7, 4, 7, 5, 6, 3, 5,
       2, 4, 4, 8, 2, 0, 8, 7, 7, 8, 6, 2, 5, 8, 6, 5, 6, 1, 2, 0, 1, 8,
       3, 4, 7, 3, 6, 7, 2, 3, 0, 5, 6, 1, 0, 2, 0,

In [16]:
er=y_test-out

In [18]:
er

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0, -8,  0,  0,  0,  2,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0, -4,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0, -3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0